enableColors: true

enableImmutableInstalls: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  eth-sig-util@*:
    dependencies:
      ethereumjs-abi: 0.6.8

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
